### ISSUE TITLE
Retrieving Information

### ISSUE THREAD

**Issue by cloud9x4** [thatguywiththatname/PCPartPicker-API#5]
Hi, i was wondering whether the codes that you've created is able to be used in order to retrieve pc parts by just searching the name and then getting information and the image of the part. I've started a website builder: https://www.wix.com on here and i have no idea how i'm supposed to create a way to search a name of a pc part and retrieve the image and data on that specific part as a result. I was wondering if you could help i've been stuck for quite a while now

**Comment by thatguywiththatname** [comment]
Currently this package does not support getting the image(s) of a part.

If you wanted to search all of the parts for a specific name, you would have to do something like

```python
from PCPartPicker_API import pcpartpicker as p

# The name of the CPU you want to find
name = "AMD Ryzen 5 2600"
cpus = p.productLists.getList("cpu")

found = None
for cpu in cpus:
    if cpu["name"] == name:
        found = cpu
        break

# the variabe "found" is now the dict for the cpu you were looking for
# or None if that cpu was not found
```

This obviously only works for CPUs, and isn't very efficient. You would have to repeat the same sort of process for each part type.

If you don't understand something to do with Python rather than this library, consider asking your question on somewhere like Stackoverflow, which will be much more helpful to you.
